namespace PjskBundle2Parts.Models;

public sealed record ExporterConfig(
    string? Body,
    string? Head,
    string? Output,
    string? Motion,
    string? HeadRoot,
    string? Master,
    string? AssetRoot,
    int? Character3dId,
    bool? KeepIntermediate,
    bool? EmitCostumeRegistries,
    bool? EmitPartPackages,
    bool? EmitRoleRuntimes,
    bool? ExportFaceMotion,
    int? PartCostume3dId,
    string? PartType,
    string? PartUnit,
    int[]? RoleCharacter3dIds,
    string? SourcePath,
    string? Manifest,
    int? PartPackageProcessConcurrency,
    int? PartPackageWorkers,
    int? PartPackageCoreCount,
    int? PartPackageShardCount,
    int? PartPackageShardIndex,
    string? AssetStudioLogLevel,
    string? RuntimeJsonOutput,
    string? AssetStudioRoot
);
